@startmindmap

* srv-device-hub
** 设备类型
*** 直接接入设备（不用通过视频平台，拥有固定IP的设备）
*** 第三方硬件平台设备（公司IoT平台或其他）
*** <&pulse>视频平台设备（海康8700、海康8200等等）
*** <s>通用设备接入协议</s>
** 功能点
*** 基础数据管理（例如设备名称、位置等）
**** 添加
**** 修改
**** 查询
**** 删除
*** 扩展信息管理（例如设备与项目关系）
**** 添加
**** 修改
**** 查询
**** 删除
*** 直播流地址获取
*** 信息同步机制（针对硬件平台设备数据或者视频平台设备数据）
*** 支持多平台接入
**** 平台管理
***** 添加
***** 修改
***** 查询
***** 删除
*** 历史数据清洗

header
硬件接入层功能点
endheader

legend right
  此次功能只涉及摄像头设备
  火成、车载行车记录仪等边缘计算设备均不在考虑范围之内
endlegend
@endmindmap
