@startuml
skinparam defaultFontName Courier
'skinparam shadowing false
'skinparam noteBackgroundColor #eee
skinparam noteBorderColor transparent
skinparam sequenceGroupBorderColor #ccc
skinparam sequenceReferenceBorderColor #ccc

title model-schedule任务调度时序图

actor       "decoder"           as DD
participant "model-schedule"    as MS
participant "decoder-center"    as DB
participant "model-dispatch"    as MD

==model-schedule时序图==

DD -> MS:1.解码图片分析(含设备场景关系)
return
|||
note over MS:注:2,5s如何补偿分析-->记录上次分析帧率:设计简单算法
MS -> MD:2.起协程,分析不同场景
return 返回分析结果
|||
MS -> DB:3.分析失败的场景,写analyze_failure_log日志\n(记录失败原因;成功不写,减少log体量)

@enduml