@startuml
autonumber
== 取流预警 ==
participant "云平台(统计服)" as st
participant "云平台(ai-center)" as center
participant "ai-bus" as bus
participant "ai-agent" as agent
participant "ai模型分析" as ai
participant "ai-task" as task

task -> ai : 调用Ai分析模型
agent <- ai : Ai模型分析失败(取流预警)

== 取流预警入库 ==
agent -> bus : 通知ai-bus取流预警
bus -> center : 报警记录生成(通知的最短间隔:1小时1次)
bus -> st : 报警记录统计
@enduml