@startuml
'autonumber
'== 取流预警 ==
''actor User as user
'participant "redis" as redis
'participant "ai-bus" as bus
'participant "ai-agent" as agent
'participant "ai模型分析" as ai
'participant "ai-task" as task
'
'task -> ai : 调用Ai分析模型
'agent <- ai : Ai模型分析失败(取流预警)
'
'== 取流预警入库(缓存) ==
'agent -> bus : 通知ai-bus取流预警
'bus --> redis : 取流报警入库(统计资源消耗使用)\n 所有GPU服务器只需要保证有一份数据即可
autonumber
== 心跳接收 ==
participant "redis" as redis
participant "ai-bus" as bus
participant "ai-agent" as agent
participant "K8S集群" as k8s

loop 60s心跳
    agent -> k8s : 向K8S请求GPU信息
    agent <-- k8s : 返回GPU信息
    agent -> bus : 将GPU信息同步至bus
    bus --> redis : GPU服务器信息入库(统计资源消耗使用)\n 所有GPU服务器只需要保证有一份数据即可
end


@enduml